package Modelos;
// Generated 16-ago-2017 18:58:25 by Hibernate Tools 4.3.1


import java.io.InputStream;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Logger;

/**
 * Automovil generated by hbm2java
 */
public class Automovil  implements java.io.Serializable {


     private Integer idAutomovil;
     private Usuario usuario;
     private Date fechaEntrada;
     private String tipo;
     private String placa;
     private String color;
     private int modelo;
     private String marca;
     private String kilometraje;
     private String ciudad;
     private String descripcion;
     private String seguro;
     private String soat;
     private String impuestos;
     private double valor;
     private String foto;
     private String estado;
     private Set compras = new HashSet(0);
     private Set tiempos = new HashSet(0);
     private Set ventas = new HashSet(0);
     private Set apartars = new HashSet(0);

    public Automovil() {
    }

	
    public Automovil(Usuario usuario, Date fechaEntrada, String tipo, String placa, String color, int modelo, String marca, String kilometraje, String ciudad, String descripcion, String seguro, String soat, String impuestos, double valor, String foto, String estado) {
        this.usuario = usuario;
        this.fechaEntrada = fechaEntrada;
        this.tipo = tipo;
        this.placa = placa;
        this.color = color;
        this.modelo = modelo;
        this.marca = marca;
        this.kilometraje = kilometraje;
        this.ciudad = ciudad;
        this.descripcion = descripcion;
        this.seguro = seguro;
        this.soat = soat;
        this.impuestos = impuestos;
        this.valor = valor;
        this.foto = foto;
        this.estado = estado;
    }
    public Automovil(int id,Usuario usuario, Date fechaEntrada, String tipo, String placa, String color, int modelo, String marca, String kilometraje, String ciudad, String descripcion, String seguro, String soat, String impuestos, double valor, String foto, String estado) {
        this.idAutomovil=id;
        this.usuario = usuario;
        this.fechaEntrada = fechaEntrada;
        this.tipo = tipo;
        this.placa = placa;
        this.color = color;
        this.modelo = modelo;
        this.marca = marca;
        this.kilometraje = kilometraje;
        this.ciudad = ciudad;
        this.descripcion = descripcion;
        this.seguro = seguro;
        this.soat = soat;
        this.impuestos = impuestos;
        this.valor = valor;
        this.foto = foto;
        this.estado = estado;
    }
//    public Automovil(Usuario usuario, Date fechaEntrada, String tipo, String placa, String color, int modelo, String marca, String kilometraje, String ciudad, String descripcion, byte[] seguro, byte[] soat, String impuestos, double valor, byte[] foto, String estado, Set compras, Set tiempos, Set ventas, Set apartars) {
//       this.usuario = usuario;
//       this.fechaEntrada = fechaEntrada;
//       this.tipo = tipo;
//       this.placa = placa;
//       this.color = color;
//       this.modelo = modelo;
//       this.marca = marca;
//       this.kilometraje = kilometraje;
//       this.ciudad = ciudad;
//       this.descripcion = descripcion;
//       this.seguro = seguro;
//       this.soat = soat;
//       this.impuestos = impuestos;
//       this.valor = valor;
//       this.foto = foto;
//       this.estado = estado;
//       this.compras = compras;
//       this.tiempos = tiempos;
//       this.ventas = ventas;
//       this.apartars = apartars;
//    }
   @Override
    public String toString() {
        return this.placa+" -- "+this.color;
    }
   
    public Integer getIdAutomovil() {
        return this.idAutomovil;
    }
    
    public void setIdAutomovil(Integer idAutomovil) {
        this.idAutomovil = idAutomovil;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public int getModelo() {
        return this.modelo;
    }
    
    public void setModelo(int modelo) {
        this.modelo = modelo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getKilometraje() {
        return this.kilometraje;
    }
    
    public void setKilometraje(String kilometraje) {
        this.kilometraje = kilometraje;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getSeguro() {
        return this.seguro;
    }
    
    public void setSeguro(String seguro) {
        this.seguro = seguro;
    }
    public String getSoat() {
        return this.soat;
    }
    
    public void setSoat(String soat) {
        this.soat = soat;
    }
    public String getImpuestos() {
        return this.impuestos;
    }
    
    public void setImpuestos(String impuestos) {
        this.impuestos = impuestos;
    }
    public double getValor() {
        return this.valor;
    }
    
    public String getValorS(){
        Double d = this.valor;
        return String.valueOf(d.doubleValue());
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getTiempos() {
        return this.tiempos;
    }
    
    public void setTiempos(Set tiempos) {
        this.tiempos = tiempos;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getApartars() {
        return this.apartars;
    }
    
    public void setApartars(Set apartars) {
        this.apartars = apartars;
    }

    
}