package Modelos;
// Generated 16-ago-2017 18:58:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int idCompra;
     private Automovil automovil;
     private Date fechaEntrega;
     private String descuento;
     private double total;
     private String estado;

    public Compra() {
    }

    public Compra(int idCompra, Automovil automovil, Date fechaEntrega, String descuento, double total, String estado) {
       this.idCompra = idCompra;
       this.automovil = automovil;
       this.fechaEntrega = fechaEntrega;
       this.descuento = descuento;
       this.total = total;
       this.estado = estado;
    }
   
    public int getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(int idCompra) {
        this.idCompra = idCompra;
    }
    public Automovil getAutomovil() {
        return this.automovil;
    }
    
    public void setAutomovil(Automovil automovil) {
        this.automovil = automovil;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public String getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(String descuento) {
        this.descuento = descuento;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


