package Modelos;
// Generated 16-ago-2017 18:58:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tiempo generated by hbm2java
 */
public class Tiempo  implements java.io.Serializable {


     private Integer idTiempo;
     private Automovil automovil;
     private Date fechaActual;
     private String descripcion;
     private String estado;

    public Tiempo() {
    }

    public Tiempo(Automovil automovil, Date fechaActual, String descripcion, String estado) {
       this.automovil = automovil;
       this.fechaActual = fechaActual;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   public Tiempo(int id,Automovil automovil, Date fechaActual, String descripcion, String estado) {
       this.idTiempo=id;
       this.automovil = automovil;
       this.fechaActual = fechaActual;
       this.descripcion = descripcion;
       this.estado = estado;
    }
    public Integer getIdTiempo() {
        return this.idTiempo;
    }
    
    public void setIdTiempo(Integer idTiempo) {
        this.idTiempo = idTiempo;
    }
    public Automovil getAutomovil() {
        return this.automovil;
    }
    
    public void setAutomovil(Automovil automovil) {
        this.automovil = automovil;
    }
    public Date getFechaActual() {
        return this.fechaActual;
    }
    
    public void setFechaActual(Date fechaActual) {
        this.fechaActual = fechaActual;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


