package Modelos;
// Generated 16-ago-2017 18:58:25 by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * Apartar generated by hbm2java
 */
public class Apartar  implements java.io.Serializable {


     private Integer idApartar;
     private Automovil automovil;
     private Usuario usuario;
     private Date fechaActual;
     private String estado;

    public Apartar() {
    }

    public Apartar(Automovil automovil, Usuario usuario, Date fechaActual, String estado) {
       this.automovil = automovil;
       this.usuario = usuario;
       this.fechaActual = fechaActual;
       this.estado = estado;
    }
    
   public Apartar(int id,Automovil automovil, Usuario usuario, Date fechaActual, String estado) {
       this.idApartar=id;
       this.automovil = automovil;
       this.usuario = usuario;
       this.fechaActual = fechaActual;
       this.estado = estado;
    }
    public Integer getIdApartar() {
        return this.idApartar;
    }
    
    public void setIdApartar(Integer idApartar) {
        this.idApartar = idApartar;
    }
    public Automovil getAutomovil() {
        return this.automovil;
    }
    
    public void setAutomovil(Automovil automovil) {
        this.automovil = automovil;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaActual() {
        return this.fechaActual;
    }
    
    public void setFechaActual(Date fechaActual) {
        this.fechaActual = fechaActual;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


